### ISSUE TITLE
PM Review: Projects

### ISSUE THREAD

**Issue by rebekahliu** [rebekahliu/KickStartNow#24]

**Comment by LochandQuay** [comment]
@rebekahliu 

Something's broken on Heroku. Try clicking one of the projects from the homepage index and you'll see what I mean (or try navigating to something like `/#/projects/2`)

**Comment by LochandQuay** [comment]
@rebekahliu 

It looks like a lot, but it's mostly small changes (and includes things that affect rewards/categories).

**General**:
- Need more and better seed data :)

**New Project form**:
  - Needs to have categories instead of indices or id's now
  - Would prefer placeholder instead of pre-filled text "hello" for title. Or an empty input since there's a label.
  - Not a fan of the incremental by 1 goal amount.
  - Not sure if this is something you can fix, but the image upload part doesn't really stand out...I think it showed up after I had already input the information in the top two fields, and it shows up at the top (which isn't intuitive)
  - It isn't clear where you're supposed to go or when the check boxes are supposed to turn green at the top (if at all). Would prefer to see something like a next button at the bottom to guide the user through adding a new project. 
  - Unclear whether the initial description is supposed to be the long one or if it's the same thing as the story description. Make it clearer by saying "Brief Description" or "Tagline". 

**Index Items & Show**:
- Index item description, if too long to fit in container, should be cut off. You can use an overflow property or look up clamping with CSS.
- Story description needs to be able to be formatted. I had a bunch of new lines and it's all bunched up. 
- Updating project form doesn't autofill with project's current information.
- After submitting new project and then navigating to categories, the categories tally of the number of projects it has should be updated with the new count.

**Errors**:
- Error: `GET https://polar-shelf-46662.herokuapp.com/undefined`
  - Actions: Explore => one category => project => Explore => different category => different project (then error shows up)
- Get rid of the iterator/unique key warning

**Comment by rebekahliu** [comment]
I fixed all the bugs from yesterday!
